[package]
name = "pathtracer"
version = "0.1.0"
authors = ["kishore-ganesh <kishore2912000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm="0.10.0"
rand = "0.8.3"
indicatif = "0.16.2"
